version: "3.8"

services:
  # Database Service
  db:
    image: mysql
    container_name: mysql_db
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: perfil
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_TIMEOUT: 28800
    restart: always
    networks:
      - backend

# Define a network for the services to communicate
networks:
  backend:
    driver: bridge